#!/bin/sh
# @name WAM-V USV
# @type Rover
# @class Rover

. ${R}etc/init.d/rc.rover_differential_defaults

param set-default SIM_GZ_EN 1
param set-default MAV_TYPE 10

# Differential drive motors
param set-default CA_AIRFRAME 6
param set-default CA_R_REV 1

# Motor assignments
param set-default CA_R0_SLEW 1.0
param set-default CA_R1_SLEW 1.0

# RC and offboard
param set-default COM_RC_IN_MODE 1
param set-default COM_OBS_AVOID 0

# GPS
param set-default COM_ARM_WO_GPS 0
param set-default EKF2_GPS_CHECK 21
param set-default EKF2_MAG_TYPE 1

# Flight modes
param set-default COM_FLTMODE1 7  # Manual
param set-default COM_FLTMODE4 6  # Offboard

rover_differential start
